# Generated by Django 5.2.1 on 2025-06-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='types',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='predefinedcategory',
            old_name='types',
            new_name='type',
        ),
    ]
