# Generated by Django 5.2.1 on 2025-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_types_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedcategory',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
