# Generated by Django 5.2.1 on 2025-06-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_predefinedcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='predefined_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predefined_category', to='category.predefinedcategory'),
        ),
    ]
