# Generated by Django 5.2.1 on 2025-06-04 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
