# Generated by Django 5.2.1 on 2025-06-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_category_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
