# Generated by Django 5.2.1 on 2025-06-02 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_achieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
