# Generated by Django 5.2.1 on 2025-06-02 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_goal_achieved_at_goal_is_achieved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 6, 2, 18, 9, 0, 92720, tzinfo=datetime.timezone.utc)),
        ),
    ]
